name: Cricket Live Feed

# Run on manual trigger or schedule
on:
  workflow_dispatch:      # manual run
  schedule:
    - cron: "* * * * *"  # runs every 30 minutes

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Run main.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          echo "Starting Cricket Live Feed script..."
          python main.py
          echo "Script finished successfully!"
